#!/bin/sh
#
# @name Aerotrain SITL
#
# @type Hexarotor x
#

. ${R}etc/init.d/rc.mc_defaults

param set-default MAV_TYPE 13

param set-default MC_PITCHRATE_P 0.056185267865657806
param set-default MC_PITCHRATE_I 0.077220581471920013
param set-default MC_PITCHRATE_D 0.001399999950081110
param set-default MC_PITCH_P 6.5
param set-default MC_ROLLRATE_P 0.043796814978122711
param set-default MC_ROLLRATE_I 0.060296110808849335
param set-default MC_ROLLRATE_D 0.001200000056996942
param set-default MC_ROLL_P 6.5
param set-default MPC_XY_VEL_I_ACC 4
param set-default MPC_XY_VEL_P_ACC 3

param set-default RTL_DESCEND_ALT 10

param set-default TRIG_INTERFACE 3
param set-default TRIG_MODE 4
param set-default MNT_MODE_IN 4
param set-default MNT_MODE_OUT 2
param set-default MAV_PROTO_VER 2

set MIXER hexa_x
